- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: Ping the Aruba switch
      ansible.builtin.ping:



#- name: Retrieve Aruba AOS-CX Running Configuration
#  hosts: all
#  collections:
#    - arubanetworks.aoscx
#  gather_facts: False
#  tasks:
#    - name: Run show running-configuration command
#      arubanetworks.aoscx.aoscx_command:
#        commands: ["show running-configuration"]
#      register: config_output
#
#    - name: Display Configuration Output
#      debug:
#        msg: "{{ config_output.stdout_lines }}"